name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload static site
        uses: actions/upload-pages-artifact@v2
        with:
          path: "./web" # Make sure index.html is inside web/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
